### ISSUE TITLE
"All Agents Stopped" when sense returns false

### ISSUE THREAD

**Issue by alexr1993** [suegy/posh-sharp#5]
After adding shoot and stopshooting behaviours, setting the jump sense to false caused all agents to stop. I expected that when this was the case the bots would use the next highest priority behaviour.

Reproduce:

Line 146 on template.cs, set s to false and  notice that that a second after starting, the console prints "all agents stopped" and the bots become unresponsive (but the application keeps running).

Code: https://github.com/alexr1993/Unreal-Bot-Coursework/tree/0feb0d6f96a919815306eb41a4afef067a376bbe

**Comment by suegy** [comment]
The issue is related to a too high frequency value for the lowest/default plan element.
If you change the default element's frequency to zero the plans should not collapse any more.
